# Generated by Django 5.1.7 on 2026-05-20 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Наименование компании')),
                ('industry', models.CharField(blank=True, max_length=200, verbose_name='Деятельность в России')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('legal_address', models.CharField(blank=True, max_length=500, verbose_name='Юридический адрес')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('tax_system', models.CharField(blank=True, choices=[('usn', 'УСН'), ('osno', 'ОСНО'), ('envd', 'ЕНВД'), ('patent', 'Патент'), ('eshn', 'ЕСХН')], max_length=20, verbose_name='Система налогообложения')),
                ('accounting_program', models.CharField(blank=True, choices=[('1c', '1С'), ('sbis', 'СБИС'), ('kontur', 'Контур'), ('moe_delo', 'Моё дело'), ('other', 'Другое')], max_length=20, verbose_name='Программа ведения бухгалтерии')),
                ('reporting_system', models.CharField(blank=True, choices=[('sbis', 'СБИС'), ('kontur', 'Контур.Экстерн'), ('taxcom', 'Такском'), ('other', 'Другое')], max_length=20, verbose_name='Система сдачи отчётности')),
                ('accountant_type', models.CharField(blank=True, choices=[('own', 'Собственный бухгалтер'), ('outsource', 'Аутсорсинг'), ('self', 'Самостоятельно'), ('none', 'Нет')], max_length=20, verbose_name='Кто ведёт учёт')),
                ('banks', models.CharField(blank=True, max_length=300, verbose_name='Список банков')),
                ('currencies', models.CharField(blank=True, default='RUB', max_length=100, verbose_name='Валюты')),
                ('has_bank_client', models.BooleanField(default=False, verbose_name='Наличие банк-клиента')),
                ('has_second_sign', models.BooleanField(default=False, verbose_name='Передача второй подписи')),
                ('avg_payments_per_month', models.PositiveIntegerField(default=0, verbose_name='Среднее кол-во платёжных поручений/мес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
