# Generated by Django 5.1.7 on 2026-05-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tariff',
            field=models.CharField(blank=True, choices=[('basic', 'Базовый'), ('business', 'Бизнес'), ('corporate', 'Корпоративный')], default='', max_length=20, verbose_name='Тариф'),
        ),
    ]
