# Generated by Django 5.1.7 on 2026-05-20 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_data_to_company(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Company = apps.get_model('accounts', 'Company')

    for user in User.objects.all():
        company = Company.objects.filter(user=user).first()
        if company:
            if not company.name and user.company_name:
                company.name = user.company_name
            company.business_type = user.business_type
            company.business_size = user.business_size
            company.tariff = user.tariff
            company.save()
        elif user.company_name:
            company = Company.objects.create(
                user=user,
                name=user.company_name,
                business_type=user.business_type,
                business_size=user.business_size,
                tariff=user.tariff,
            )
        else:
            continue

        user.active_company = company
        user.save()


def reverse_migrate(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if user.active_company:
            c = user.active_company
            user.company_name = c.name
            user.business_type = c.business_type
            user.business_size = c.business_size
            user.tariff = c.tariff
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_tariff'),
    ]

    operations = [
        # 1. Добавляем новые поля в Company
        migrations.AddField(
            model_name='company',
            name='business_size',
            field=models.CharField(blank=True, choices=[('1', 'Менее 10 сотрудников'), ('2', '10–50 сотрудников'), ('3', '50–200 сотрудников'), ('4', '200–500 сотрудников'), ('5', '500–1000 сотрудников'), ('6', 'Более 1000 сотрудников')], max_length=5, verbose_name='Размер бизнеса'),
        ),
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Индивидуальный предприниматель'), ('llc', 'ООО'), ('jsc', 'АО'), ('other', 'Другое')], max_length=20, verbose_name='Тип бизнеса'),
        ),
        migrations.AddField(
            model_name='company',
            name='tariff',
            field=models.CharField(blank=True, choices=[('basic', 'Базовый'), ('business', 'Бизнес'), ('corporate', 'Корпоративный')], default='', max_length=20, verbose_name='Тариф'),
        ),
        # 2. Меняем OneToOneField → ForeignKey в Company.user
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        # 3. Добавляем User.active_company
        migrations.AddField(
            model_name='user',
            name='active_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='accounts.company', verbose_name='Активная компания'),
        ),
        # 4. Переносим данные из User → Company и устанавливаем active_company
        migrations.RunPython(migrate_data_to_company, reverse_migrate),
        # 5. Удаляем старые поля из User
        migrations.RemoveField(model_name='user', name='business_size'),
        migrations.RemoveField(model_name='user', name='business_type'),
        migrations.RemoveField(model_name='user', name='company_name'),
        migrations.RemoveField(model_name='user', name='tariff'),
    ]
