# Generated by Django 5.1.7 on 2026-05-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_refactor_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_trips_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Командировки в месяц'),
        ),
        migrations.AddField(
            model_name='company',
            name='contracts_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество договоров с покупателями и поставщиками'),
        ),
        migrations.AddField(
            model_name='company',
            name='counterparty_reconciliation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Частота сверок с контрагентами'),
        ),
        migrations.AddField(
            model_name='company',
            name='document_responsible',
            field=models.CharField(blank=True, choices=[('invoices', 'Накладные'), ('acts', 'Акты'), ('all', 'Все документы'), ('other', 'Другое')], max_length=20, verbose_name='Ответственные за оформление документов'),
        ),
        migrations.AddField(
            model_name='company',
            name='employees_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество сотрудников (штат + ГПХ)'),
        ),
        migrations.AddField(
            model_name='company',
            name='entertainment_expenses',
            field=models.CharField(blank=True, choices=[('frequent', 'Частые'), ('rare', 'Редкие'), ('none', 'Нет')], max_length=20, verbose_name='Представительские расходы'),
        ),
        migrations.AddField(
            model_name='company',
            name='expense_reports_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Авансовые отчёты в месяц'),
        ),
        migrations.AddField(
            model_name='company',
            name='fixed_assets_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество основных средств и НМА'),
        ),
        migrations.AddField(
            model_name='company',
            name='foreign_currency_operations',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество валютных операций (импорт/экспорт)'),
        ),
        migrations.AddField(
            model_name='company',
            name='has_corporate_cards',
            field=models.BooleanField(default=False, verbose_name='Корпоративные карты'),
        ),
        migrations.AddField(
            model_name='company',
            name='has_customs',
            field=models.BooleanField(default=False, verbose_name='Таможенные операции'),
        ),
        migrations.AddField(
            model_name='company',
            name='has_property',
            field=models.CharField(blank=True, max_length=300, verbose_name='Наличие склада, недвижимости, земли'),
        ),
        migrations.AddField(
            model_name='company',
            name='hr_program',
            field=models.CharField(blank=True, choices=[('1c_zup', '1С:ЗУП'), ('1c', '1С'), ('kontur', 'Контур.Персонал'), ('other', 'Другое')], max_length=20, verbose_name='Программа для кадрового учёта'),
        ),
        migrations.AddField(
            model_name='company',
            name='needs_management_report',
            field=models.BooleanField(default=False, verbose_name='Управленческая отчётность'),
        ),
        migrations.AddField(
            model_name='company',
            name='non_resident_contracts',
            field=models.PositiveIntegerField(default=0, verbose_name='Контракты с нерезидентами'),
        ),
        migrations.AddField(
            model_name='company',
            name='separate_divisions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Обособленные подразделения'),
        ),
        migrations.AddField(
            model_name='company',
            name='vehicles_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Автомобилей на балансе'),
        ),
    ]
